### PR TITLE
FIX: quit loop when path is found, custom path first, fix typo

### PR DESCRIPTION
**Pull request by Tavrin**
As of now the path loop continues even if the directory was found, as for the paths list, anaconda comes after miniconda (but we want to use miniconda if we have both), so this fix places the custom path (if added) first then checks the paths like before and quits the loop when it's found.

### CODE REVIEW

**Comment by zlalvani** [comment]
Since you're in this part of the code anyway, might be worth fixing the typo in the variable name: `cutom_conda_path` -> `custom_conda_path`

I was about to make a PR to do it lol

**Comment by Tavrin** [comment]
You're right, I didn't see it at first haha, I juste updated my PR to include it

**Review by Hafiidz — APPROVED** [review]
was about to submit the same pull request, looks good

**Review by Hafiidz — APPROVED** [review]
was about to send the same pull request, looks good

**Pull request merged**
