### PR TITLE
Finish moving all docker paths to sd

### LINKED ISSUE #45: docker-compose up error: No module named 'k_diffusion'
Ran `docker-compose up` and getting an error `ModuleNotFoundError: No module named 'k_diffusion'. Full output here:

```sh
$ docker-compose up
[+] Running 1/0
 ⠿ Container sd  Created                                                                                                                         0.0s
Attaching to sd
sd  | Validating model files...
sd  | checking model.ckpt...
sd  | model.ckpt is valid!
sd  | 
sd  | checking GFPGANv1.3.pth...
sd  | GFPGANv1.3.pth is valid!
sd  | 
sd  | checking RealESRGAN_x4plus.pth...
sd  | RealESRGAN_x4plus.pth is valid!
sd  | 
sd  | checking RealESRGAN_x4plus_anime_6B.pth...
sd  | RealESRGAN_x4plus_anime_6B.pth is valid!
sd  | 
sd  | Relauncher: Launching...
sd  | Traceback (most recent call last):
sd  |   File "scripts/webui.py", line 36, in <module>
sd  |     import k_diffusion as K
sd  | ModuleNotFoundError: No module named 'k_diffusion'
sd  | Relauncher: Process is ending. Relaunching in 0.5s...
sd  | Relauncher: Launching...
sd  |   Relaunch count: 1
sd  | Traceback (most recent call last):
sd  |   File "scripts/webui.py", line 36, in <module>
sd  |     import k_diffusion as K
sd  | ModuleNotFoundError: No module named 'k_diffusion'
sd  | Relauncher: Process is ending. Relaunching in 0.5s...
```

### PR DESCRIPTION
**Pull request by oc013**
* Move conda env setup to container instead of image
* Create docker-reset script to help with botched installs

The issue was most likely due to setting up the conda environment in the docker image which placed some files in `src` that were then overwritten/removed when the volume with the project's code was mounted.

Resolves #45

### CODE REVIEW

**Comment by ChrisAcrobat** [comment]
I cloned your [patch-docker-move-src-path](https://github.com/oc013/stable-diffusion/tree/patch-docker-move-src-path) branch and executed `docker-compose up`. Got this:
````
Creating network "stable-diffusion_default" with the default driver
Creating volume "stable-diffusion_conda_env" with default driver
Creating volume "stable-diffusion_root_profile" with default driver
Creating sd ... done
Attaching to sd
sd                   | /bin/bash: /src/entrypoint.sh: /bin/bash^M: bad interpreter: No such file or directory
sd exited with code 126
```

**Comment by oc013** [comment]
@ChrisAcrobat you still are running on the old docker image and need to rebuild it. Everything was moved from `/src/` to the `/sd` directory to reduce confusion in the future

Please try out first which should pick up the changes and rebuild only what is neccessary:
`docker compose up --build`

If that fails this command will do a full rebuild:
`docker compose build --no-cache`

If that fails use/refer to the `docker-reset.sh` script for more possible steps

**Comment by ChrisAcrobat** [comment]
I reset everything by execute everything in `docker-reset.sh` by hand (I'm running Windows), but still geting the same problem.
```
Creating network "stable-diffusion_default" with the default driver
Creating volume "stable-diffusion_conda_env" with default driver
Creating volume "stable-diffusion_root_profile" with default driver
Creating sd ... done
Attaching to sd
sd                   | /bin/bash: /src/entrypoint.sh: /bin/bash^M: bad interpreter: No such file or directory
sd exited with code 126
```
Would uploading the image to a repo solve future problems lite this? Like [this](https://github.com/marketplace/actions/build-and-publish-docker-image-to-new-github-packages-registry). 👈 Haven't tried that my self.

**Comment by oc013** [comment]
@ChrisAcrobat  Yes it might, but it's extra overhead right now to make the build and publish process and this is not my repository.  We should be able to resolve without it though. I will assume you are using Docker Desktop, hopefully this helps (I'm just going off of screenshots I can find of the desktop app):

* In the Containers / Apps tab, make sure that the container is fully stopped.
* In the same tab delete the container 
* In images tab, click more options and remove for any copies there named `stabile-diffusion` 
* In the volumes tab, delete the two volumes `conda_env` and `root_profile`, hopefully they're prefixed with `stabile-diffusion`
* Now `docker-compose up`
* 
If the first thing you see is not building the container, the old data was not fully removed.  You should see something like this before what you posted:
```
$ docker compose up
[+] Building 98.8s (10/10) FINISHED
=> [internal] load build definition from Dockerfile
=> => transferring dockerfile: 644B
```

PS I caught the typo where I called it "stabile" and changed to the correct spelling.   This probably will help if you pull that down as well since it should label everything differently.

**Comment by ChrisAcrobat** [comment]
Yes, Docker Desktop (not Docker for Windows).

I removed everything from the Docker UI (as I also have done on every other time as a precaution), but still no difference.
A thing that I have noticed: Isn't the build time quite fast (`[+] Building 1.2s (13/13) FINISHED`) for doing everything from scratch?`Is there a cache that I am missing?
```
[+] Building 1.2s (13/13) FINISHED
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 32B                                                                                0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 2B                                                                                    0.0s
 => [internal] load metadata for docker.io/nvidia/cuda:11.3.1-runtime-ubuntu20.04                                  1.0s
 => [auth] nvidia/cuda:pull token for registry-1.docker.io                                                         0.0s
 => [internal] load build context                                                                                  0.0s
 => => transferring context: 99B                                                                                   0.0s
 => [1/7] FROM docker.io/nvidia/cuda:11.3.1-runtime-ubuntu20.04@sha256:b5bc2fd699c8fcb27e0701b90ecd6526a65adce782  0.0s
 => CACHED [2/7] RUN apt update &&     apt install -y libglib2.0-0 wget &&     apt-get clean &&     rm -rf /var/l  0.0s
 => CACHED [3/7] RUN wget -O ~/miniconda.sh -q --show-progress --progress=bar:force https://repo.anaconda.com/min  0.0s
 => CACHED [4/7] COPY ./environment.yaml ./setup.py /src/                                                          0.0s
 => CACHED [5/7] WORKDIR /src                                                                                      0.0s
 => CACHED [6/7] RUN conda env create -f /src/environment.yaml &&     echo "source activate ldm" > /root/.bashrc   0.0s
 => CACHED [7/7] COPY ./entrypoint.sh /src/                                                                        0.0s
 => exporting to image                                                                                             0.1s
 => => exporting layers                                                                                            0.0s
 => => writing image sha256:fb574cf9d3eb66af43c5461ac6f78e08997a505ec382e3d40d380e34e5b3bd58                       0.0s
 => => naming to docker.io/library/stable-diffusion_stabile-diffusion                                              0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
[+] Running 4/4
 - Network stable-diffusion_default        Created                                                                 0.0s
 - Volume "stable-diffusion_conda_env"     Created                                                                 0.0s
 - Volume "stable-diffusion_root_profile"  Created                                                                 0.0s
 - Container sd                            Created                                                                60.4s
Attaching to sd
sd  | /bin/bash: /src/entrypoint.sh: /bin/bash^M: bad interpreter: No such file or directory
sd exited with code 126
```

**Comment by oc013** [comment]
@ChrisAcrobat Yes you can see it says `CACHED [2/7]` etc so it still has some layers stored somewhere. 

Can you try to pull down my last couple commits, I see it's still trying to use `stabile_diffusion` and I corrected it since to make sure we're on the same page.

**Comment by ChrisAcrobat** [comment]
I'll try latar. I'm AFK a few ours.

**Comment by hlky** [comment]
I take it this isn't ready to merge yet?

**Comment by oc013** [comment]
@hlky I think it is. I completely deleted and rebuilt from scratch like 10 times and have been running it since the last commit with the new font instruction.  Could wait for @ChrisAcrobat or someone to test it out on their windows machine I guess.

**Comment by ChrisAcrobat** [comment]
I now tried:
```
docker system prune -a
git clone https://github.com/hlky/stable-diffusion.git
cd stable-diffusion
docker-compose up
```
And got:
```
Creating network "stable-diffusion_default" with the default driver
Building stable-diffusion
[+] Building 206.5s (12/12) FINISHED
 => [internal] load build definition from Dockerfile                                                               0.1s
 => => transferring dockerfile: 757B                                                                               0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 2B                                                                                    0.0s
 => [internal] load metadata for docker.io/nvidia/cuda:11.3.1-runtime-ubuntu20.04                                  2.3s
 => [auth] nvidia/cuda:pull token for registry-1.docker.io                                                         0.0s
 => [internal] load build context                                                                                  0.1s
 => => transferring context: 760.79kB                                                                              0.0s
 => [1/6] FROM docker.io/nvidia/cuda:11.3.1-runtime-ubuntu20.04@sha256:b5bc2fd699c8fcb27e0701b90ecd6526a65adce7  170.8s
 => => resolve docker.io/nvidia/cuda:11.3.1-runtime-ubuntu20.04@sha256:b5bc2fd699c8fcb27e0701b90ecd6526a65adce782  0.0s
 => => sha256:e1bae4c1f40fdf955a379a4700c3f4f631aedecfefc8b2c1f27514ca78d84354 11.32MB / 11.32MB                   6.2s
 => => sha256:b5bc2fd699c8fcb27e0701b90ecd6526a65adce782d48fde9ab04938d7b92cd9 743B / 743B                         0.0s
 => => sha256:98322ec5f7b9804b17427a9264d8b3cf70c028d0ec9033ffe2af17f8ca59e81d 9.12kB / 9.12kB                     0.0s
 => => sha256:d5fd17ec1767521cf97f61568096bfc9a7cd9c2d149576a7b43930c5a97062b0 28.57MB / 28.57MB                  13.6s
 => => sha256:602a45a9c0c53b3d3e098c00c9eb2cfc4e5e682368b3c332a8b369f7dbe3eeaa 7.93MB / 7.93MB                     2.1s
 => => sha256:e950226b84bf5f9746893d29ea343dddec82b9db357b14cb6dba908372095f8c 1.79kB / 1.79kB                     0.0s
 => => sha256:d9d586ab25108661e1d6c8212e8252ad8d6fd368a8769b16bf05fb6cb16edd00 187B / 187B                         2.3s
 => => sha256:2b44adc78060afe2fe60578baf05e2b084bf1c7e17fef8742f7259fb5469283d 6.43kB / 6.43kB                     2.4s
 => => sha256:cd4d84563a605732aa22296e0bd95a61f5285f4bbd0bc4d4cfa6ae6748bd8451 1.02GB / 1.02GB                   149.6s
 => => sha256:e19a4e23074d201cdc29041210ab2e001552b0ff5f2998aa11dc0f1fd310cb7f 62.05kB / 62.05kB                   6.4s
 => => extracting sha256:d5fd17ec1767521cf97f61568096bfc9a7cd9c2d149576a7b43930c5a97062b0                          1.0s
 => => extracting sha256:602a45a9c0c53b3d3e098c00c9eb2cfc4e5e682368b3c332a8b369f7dbe3eeaa                          0.2s
 => => extracting sha256:e1bae4c1f40fdf955a379a4700c3f4f631aedecfefc8b2c1f27514ca78d84354                          0.3s
 => => extracting sha256:d9d586ab25108661e1d6c8212e8252ad8d6fd368a8769b16bf05fb6cb16edd00                          0.0s
 => => extracting sha256:2b44adc78060afe2fe60578baf05e2b084bf1c7e17fef8742f7259fb5469283d                          0.0s
 => => extracting sha256:cd4d84563a605732aa22296e0bd95a61f5285f4bbd0bc4d4cfa6ae6748bd8451                         20.3s
 => => extracting sha256:e19a4e23074d201cdc29041210ab2e001552b0ff5f2998aa11dc0f1fd310cb7f                          0.0s
 => [2/6] WORKDIR /sd                                                                                              0.5s
 => [3/6] RUN apt-get update &&     apt-get install -y libglib2.0-0 wget &&     apt-get clean &&     rm -rf /var  15.9s
 => [4/6] RUN wget -O ~/miniconda.sh -q --show-progress --progress=bar:force https://repo.anaconda.com/miniconda  14.2s
 => [5/6] COPY /data/DejaVuSans.ttf /usr/share/fonts/truetype/                                                     0.1s
 => [6/6] COPY ./entrypoint.sh /sd/                                                                                0.1s
 => exporting to image                                                                                             2.5s
 => => exporting layers                                                                                            2.5s
 => => writing image sha256:5d68537cb165bbd79f945f5f8f6fba66fe5837780610a9793653548994fbe3f8                       0.0s
 => => naming to docker.io/library/stable-diffusion_stable-diffusion                                               0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
WARNING: Image for service stable-diffusion was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating sd ... done
Attaching to sd
sd                  | /bin/bash: /sd/entrypoint.sh: /bin/bash^M: bad interpreter: No such file or directory
sd exited with code 126
```
So still the same problem, for me at least. Anyone else using Windows (11) that have this issue or at least can confirm a successful installation?

**Comment by oc013** [comment]
@ChrisAcrobat Okay, so you're definitely on the latest version now I can see.  I think looking at that final error message a bit closer the key for your issue is the `^M` which indicates that somehow the file got converted to windows-based newlines. This could possibly happen on checkout of the git repo. For example this answer where you or windows default git would have converted newline characters: https://stackoverflow.com/a/40537078

If you type `git status` you can see what files were modified on your system from the repository.  Then type `git diff ./entrypoint.sh` and I'll guess you'll see something at the end of each line?  If so try to run `git restore ./entrypoint.sh` and it should hopefully revert it. If not please try the suggestion in the article I linked above.

**Comment by ChrisAcrobat** [comment]
Good catch @oc013! I'm working on a fix @hlky and will push my own PR after I have confirmed the solution.

**Comment by oc013** [comment]
@ChrisAcrobat nice, glad it works :)

**Comment by hlky** [comment]
@oc013 good catch

@ChrisAcrobat if this works for you i'll merge, thanks

**Comment by ChrisAcrobat** [comment]
Thanks for the help, @oc013!
# 🥳

**Comment by ChrisAcrobat** [comment]
@hlky looks like it, `sd` is loading a lot of stuff now. 😄 But I'll wait until I had generate a riding astronaut.

**Comment by ChrisAcrobat** [comment]
It looks like it's stuck.
```
sd                  | LatentDiffusion: Running in eps-prediction mode
sd                  | entrypoint.sh: Process is ending. Relaunching in 0.5s...
sd                  | /sd/entrypoint.sh: line 89:   657 Killed                  python -u scripts/webui.py
sd                  | entrypoint.sh: Launching...'
sd                  | Relaunch count: 5
sd                  | Loaded GFPGAN
sd                  | Loaded RealESRGAN with model RealESRGAN_x4plus
sd                  | Loading model from models/ldm/stable-diffusion-v1/model.ckpt
sd                  | Global Step: 470000
sd                  | LatentDiffusion: Running in eps-prediction mode
```

**Comment by oc013** [comment]
@ChrisAcrobat can you verify that the newline issue didn't occur in other files?  what does `git status` look like?

**Comment by ChrisAcrobat** [comment]
`git status`:
```
On branch pr
Your branch is up to date with 'origin/pr'.

nothing to commit, working tree clean
```
I don't think `.gitattributes` `text eol=lf` leaves anything visibel. I also made a clean clone, FYI.

By the way, we can continue this discussion on my PR (#71), I feel this is pretty unrelated to your Docker script.

**Pull request merged**
