### PR TITLE
.gitattributes: common template

### PR DESCRIPTION
**Pull request by Lex-DRL**
Template catching most of the file formats for a regular Python project which might get related to webdev in a future (python, OS scripts/configs, images, html, css, etc.)
Almost all the text files are forced to be LF. The only exceptions are `*.txt` and purely windows formats (csharp, bat, cmd).
Catches both lower- and uppercase extensions, with any mix of casing.

### CODE REVIEW

**Comment by oc013** [comment]
Please note webgui code is synced from a different repository, so line endings should be updated there to make the changes stick.

**Comment by Lex-DRL** [comment]
@oc013 , created: hlky/stable-diffusion-webui/246

**Comment by ChrisAcrobat** [comment]
@Lex-DRL: Any reason for `*.sh text eol=lf` not being included? `*.py text eol=lf` was merged by mistake and I have no problem with it being excluded.

**Comment by oc013** [comment]
@ChrisAcrobat Believe shell scripts would be covered by `*.[Ss][Hh] diff=bash text eol=lf`  It's a small regex to cover upper and lowercase of the each letter

**Comment by Lex-DRL** [comment]
@oc013
> It's a small regex

Unfortunately, it's not exactly a regex. https://en.wikipedia.org/wiki/Glob_(programming)

I personally hate glob syntax, but I guess it's a good middle ground between complexity and flexability. If it wasn't for glob limitations, I wouldn't have to do all that `[Aa][Bb][Cc]` nonsense.

**Comment by hlky** [comment]
image

not going to merge this, sorry, not an issue

**Comment by oc013** [comment]
image
It is whitespace only changes. One way to fix PR #71

**Comment by hlky** [comment]
yes and its going to cause issues, it already has

**Comment by hlky** [comment]
i cant merge changes from dev without all the line endings changing meaning i cant easily revert anything in the future
this has f**cked everything up imo, someone needs to revert the line ending changes on dev, im too annoyed with this f*ck up to do it

**Comment by Lex-DRL** [comment]
@hlky 
> yes and its going to cause issues, it already has

That's exactly the reason why `.gitattributes` with `* text=auto eol=lf` should be committed at the very start of a repo. I usually do it right after an empty initial commit. Just a suggestion for your future work.

Anyway, thanks for your time and keep up the good work! Your GUI us AWESOME 👍🏻

**Pull request closed without merging**
