### PR TITLE
fixed docker build in linux

### PR DESCRIPTION
**Pull request by endomorphosis**

### CODE REVIEW

**Comment by endomorphosis** [comment]
I made some modifications, so that this will docker build correctly.

when it launches, it iterates through all of the gpu's on the system, and will launch 1 instance per GPU, then announce the instances and GPUs that are running, to a separate server.

**Comment by oc013** [comment]
what a mess, use the docker-compose file

**Comment by endomorphosis** [comment]
I am going to add a websocket connection to a separate server, so that the other server can dispatch jobs to workers, and I can just run a multiple of these docker containers as workers. I will look into your advice and will clean up the repo when its done.

**Review by oc013 — COMMENTED** [review]
This PR seems to have missed using the expected mounted volumes and overcompensated. 

Also the extra copy of webui.py, moving the model file locations, changing the env name inside the container, adding a different conda environment, reverting a dependency away from the repo's expected one for `facexlib`, pointing to some non-existent "announce host", leaving a test bash script.

Suggest closing this PR and re-approaching the problem in a more non-invasive way that also doesn't break things for users of the repository that don't use docker.

**Pull request closed without merging**
